# Generated by Django 3.0 on 2020-03-30 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomedepartamento', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'departamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('nascimento', models.DateField()),
                ('rg', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=15)),
                ('telefone', models.CharField(blank=True, max_length=12, null=True)),
                ('cnh', models.CharField(blank=True, max_length=12, null=True)),
                ('cnh_tipo', models.CharField(blank=True, max_length=10, null=True)),
                ('sexo', models.CharField(max_length=1)),
                ('funcao', models.CharField(max_length=20)),
                ('foto_colaborador', models.BinaryField(blank=True, null=True)),
                ('departamento', models.ForeignKey(db_column='departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='CoreApp.Departamento')),
            ],
            options={
                'db_table': 'colaborador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomefuncao', models.CharField(max_length=20)),
                ('departamento', models.ForeignKey(db_column='departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='CoreApp.Departamento')),
            ],
            options={
                'db_table': 'funcao',
                'managed': True,
                'unique_together': {('id', 'departamento')},
            },
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_formacao', models.CharField(max_length=14)),
                ('nome_curso', models.CharField(max_length=50)),
                ('instituicao', models.CharField(max_length=50)),
                ('dt_inicio', models.DateField()),
                ('dt_fim', models.DateField()),
                ('colaborador', models.ForeignKey(db_column='colaborador', on_delete=django.db.models.deletion.DO_NOTHING, to='CoreApp.Colaborador')),
            ],
            options={
                'db_table': 'formacao',
                'managed': True,
                'unique_together': {('id', 'colaborador')},
            },
        ),
    ]
